### ISSUE TITLE
Players report extreme lag spikes on client while using this mod server-side only

### ISSUE THREAD

**Issue by Neubulae** [dexman545/Iguana-in-a-Blanket#5]
After I installed this mod on server, a few players started complaining their game starting to freeze after few seconds of gaming. I didn't announce that the mod is installed server-side only and I quickly removed the mod. Afterwards the complaints stopped. It's kinda weird that this sorts of problem happens. How do I provide a client-side report if necessary?

**Comment by dexman545** [comment]
I would need the log of the client that freezes.

**Comment by Neubulae** [comment]
> I would need the log of the client that freezes.

Ok, I'd provide a log if I can

**Comment by Neubulae** [comment]
> I would need the log of the client that freezes.

While the log file is 54 MB big I found this part always repeating...:
`[12:53:20] [main/FATAL]: Error executing task on Client
java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!
	at net.minecraft.class_1329.<init>(class_1329.java:21) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_634.method_11149(class_634.java:2167) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_2781.method_11936(class_2781.java:70) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_2781.method_11054(class_2781.java:15) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.15.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.15.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.15.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.15.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-1.15.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.6+build.179.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.6+build.179.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.6+build.179.jar:?]`

**Comment by dexman545** [comment]
Is this from the client?
What are your config values for entity attributes (on the server)?
This is server-side only, right?

**Comment by Neubulae** [comment]
> Is this from the client?
> What are your config values for entity attributes (on the server)?
> This is server-side only, right?

Right. Other than client-side lag the server also experiences a bit of high mspt… lemme send you the config

**Comment by dexman545** [comment]
Since all you want is stack size changes, this is a version with pretty much everything disabled but that.
https://github.com/dexman545/Iguana-in-a-Blanket/releases/tag/special

**Comment by Neubulae** [comment]
> Since all you want is stack size changes, this is a version with pretty much everything disabled but that.
> https://github.com/dexman545/Iguana-in-a-Blanket/releases/tag/special

Oh... thx.

**Comment by Neubulae** [comment]
[iguana.txt](https://github.com/dexman545/Iguana-in-a-Blanket/files/4259336/iguana.txt)
[multistack.lua.txt](https://github.com/dexman545/Iguana-in-a-Blanket/files/4259337/multistack.lua.txt)
These are the configs.
